# Generated by Django 4.2.27 on 2026-01-12 09:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fake_news_count',
            field=models.IntegerField(default=0, help_text='Number of fake news posts detected'),
        ),
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='messages_blocked',
            field=models.IntegerField(default=0, help_text='Number of toxic messages blocked'),
        ),
        migrations.AddField(
            model_name='user',
            name='messages_sent',
            field=models.IntegerField(default=0, help_text='Total number of messages sent'),
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='reports_received',
            field=models.IntegerField(default=0, help_text='Number of times this user was reported'),
        ),
        migrations.AddField(
            model_name='user',
            name='toxicity_score',
            field=models.FloatField(default=0.0, help_text='Average toxicity score (0-1)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='custom_user_groups', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_permissions', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
